# Generated by Django 5.1.5 on 2026-05-05 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('typingjob', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='name',
            field=models.CharField(default='Unknown', max_length=50),
            preserve_default=False,
        ),
    ]
